spring:
  application:
    mame: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.w4you.notificationservice.OrderCreatedEvent

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      #      defaultZone: http://eureka:password@localhost:8761/eureka
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0